Repository SpreadSheets600/Budget-Tracker, pull requests merged in 2024-10, with the labels that each got.

#3 added night mode
  App.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#6 Added customtkinter module, enhanced UI UX
  App.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#8 Budget Tracker | Make Data Permanent: Enhance the database functionality to ensure persistent data storage, so users can retrieve past transactions after restarting the app.
  App.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 Added CONTRIBUTING.md and CODE_OF_CONDUCT.md to the project
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#10 Fixed Display for CustomTkinter
  App.py
  README.md
  requirements.txt
Labels: bug, hacktoberfest, hacktoberfest-accepted

#34 [FIX] Fix notification position
  src/Main.py
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#35 Update Database.py
  src/utils/Database.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#36 Issue 33 add .gitignore file
  .gitignore
  src/Icon.ico
  src/Main.py
  src/utils/Export.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
